project_id = "uxeksjeievmktvrkieja"

[functions.ai-chat]
verify_jwt = false

[functions.generate-trip-image]
verify_jwt = true

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false
